import { SecureLayout } from "@/components/SecurePage";
import { Providers } from "@/utils/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LoginUpLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <SecureLayout loginPage={true}>
                        {children}
                    </SecureLayout>
                </Providers>
            </body>
        </html>
    );
}
